### ISSUE TITLE
Can't using version 1.0.140  on mac m1

### ISSUE THREAD

**Issue by KarlManong** [Eugeny/terminus#4022]
after fresh installed, it display nothing, and can't quit
![image](https://user-images.githubusercontent.com/2627662/122710493-ef7df680-d292-11eb-90d8-cbd483bfc89c.png)

**Comment by kaven85** [comment]
same to me

**Comment by xgone** [comment]
俺也一样

**Comment by Eugeny** [comment]
I unfortunately don't have an M1 machine available right now - can you check if running `/Applications/Terminus.app/Contents/MacOS/Terminus --debug` from the macOS terminal gives you debug output? Thanks.

**Comment by helbaco** [comment]
same on my maschine,

➜  ~ /Applications/Terminus.app/Contents/MacOS/Terminus --debug
dyld: lazy symbol binding failed: Symbol not found: _GetAarch64Info
  Referenced from: /var/folders/01/7t2plxlx68d6v8y0hx873n3c0000gn/T/.org.terminus.IRvqrx
  Expected in: flat namespace

dyld: Symbol not found: _GetAarch64Info
  Referenced from: /var/folders/01/7t2plxlx68d6v8y0hx873n3c0000gn/T/.org.terminus.IRvqrx
  Expected in: flat namespace

[0621/104332.373584:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x16af00000, 0x8000): (os/kern) protection failure (2)

**Comment by darox** [comment]
Same on my machine..

**Comment by altholin** [comment]
same on my m1

**Comment by neoswallow** [comment]
I can confirm that 1.0.140 and 1.0.141 both not working on MacMini M1, macOS 11.4.
Reverting back to 1.0.139.

**Comment by Eugeny** [comment]
Thanks. Could you please upload the file mentioned in the log (`/var/folders/01/<random>/T/.org.terminus.<random>`)? It will only exist until you close the window.

**Comment by neoswallow** [comment]
140
└> /Applications/Terminus.app/Contents/MacOS/Terminus --debug
dyld: lazy symbol binding failed: Symbol not found: _GetAarch64Info
  Referenced from: /var/folders/z3/l06ymmzs0kz73mzqh4g9bhpr0000gn/T/.org.terminus.Nm5ttq
  Expected in: flat namespace

dyld: Symbol not found: _GetAarch64Info
  Referenced from: /var/folders/z3/l06ymmzs0kz73mzqh4g9bhpr0000gn/T/.org.terminus.Nm5ttq
  Expected in: flat namespace

141
└> /Applications/Terminus.app/Contents/MacOS/Terminus --debug
dyld: lazy symbol binding failed: Symbol not found: _GetAarch64Info
  Referenced from: /var/folders/z3/l06ymmzs0kz73mzqh4g9bhpr0000gn/T/.org.terminus.Z8fcKl
  Expected in: flat namespace

dyld: Symbol not found: _GetAarch64Info
  Referenced from: /var/folders/z3/l06ymmzs0kz73mzqh4g9bhpr0000gn/T/.org.terminus.Z8fcKl
  Expected in: flat namespace
[org.terminus.Nm5ttq-140.zip](https://github.com/Eugeny/terminus/files/6716418/org.terminus.Nm5ttq-140.zip)
[org.terminus.Z8fcKl-141.zip](https://github.com/Eugeny/terminus/files/6716419/org.terminus.Z8fcKl-141.zip)

**Comment by Eugeny** [comment]
Thanks. Could you please try this build? https://nightly.link/Eugeny/terminus/workflows/macos/master/macOS%20.pkg%20%28arm64%29.zip

**Comment by helbaco** [comment]
works on my machine, thank you

**Comment by neoswallow** [comment]
Yes, this one work 👍🏼

**Comment by neoswallow** [comment]
I'm not sure if this is same build as 142 but 142 works, too.

**Comment by Eugeny** [comment]
Yep, I've just released it as v142, thanks for testing!
